### ISSUE TITLE
Can't resolve 'framer-motion'

### ISSUE THREAD

**Issue by FabianMonjes** [reflex-dev/hacktoberfest#2]
when i put reflex run and open localhost:3000 for the first time give me this 
![image](https://github.com/reflex-dev/hacktoberfest/assets/53021540/6ffb09bb-b6f3-477c-8a91-b9f173305b7e)

**Comment by masenf** [comment]
I think this might be an upstream issue that needs to be investigated. Ran into this myself earlier today as I was working in a dev branch, but didn't realize it was affecting released versions

**Comment by Alek99** [comment]
I don't seem to get this issue but I have some ideas to what could be happening one sec

**Comment by Alek99** [comment]
> when i put reflex run and open localhost:3000 for the first time give me this
> ![image](https://user-images.githubusercontent.com/53021540/272435141-6ffb09bb-b6f3-477c-8a91-b9f173305b7e.png)

Can you provide some more details what  OS, Reflex version, python version. Also if you can can you look .web folder and run the command `npm list`

**Comment by Alek99** [comment]
Ok thanks for the feedback it seems like some were getting this issue for a brief time period today and yesterday but it seems to not be occurring on a regular basis, we are investigating more and will have fix in the release coming out this week.
