### ISSUE TITLE
Expense Tracker

### ISSUE THREAD

**Issue by CapedDemon** [reflex-dev/hacktoberfest#3]
Hey There. I want to contribute a program an interesting project. This is an expense tracker which will help user to keep a track record of their expenses monthly and weekly. This will also show their expense data through graph and provide where more money is used. Please assign me this task for the hacktoberfest. I am not sure where to submit this project - in interactive_db or data_visualizations ? Please tell. Looking forward to it...

**Comment by Alek99** [comment]
Sounds good! You can submit this to the interactive_db

**Comment by CapedDemon** [comment]
Closing the issue

**Comment by CapedDemon** [comment]
Closing the issue
